Dokify\Domain\Model\Documents\Documents:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  table: documents
  repositoryClass: Dokify\Infrastructure\Domain\Model\Documents\DoctrineDocumentsRepository
  fields:
    name:
      type: string
      unique: true
    created_at:
      type: datetime
  manyToOne:
    employee:
      targetEntity: Dokify\Domain\Model\Employee\Employee:
      inversedBy: employee
      joinColumn:
        name: documents_id
        referencedColumnName: id
        onDelete: RESTRICT
        onUpdate: RESTRICT
        nullable: false
      cascade: ["persist", "merge"]