CodeGenerator\Domain\Model\UserCode\UserCode:
  type: entity
  id:
    id:
      type: integer
      generator:
        strategy: AUTO
  table: app_user_code
  repositoryClass: CodeGenerator\Infrastructure\Domain\Model\UserCode\DoctrineUserCodeRepository
  fields:
    ip_address:
      type: string
      nullable: true
    createdAt:
      type: datetime
  uniqueConstraints:
    register_idx:
      columns: [coupon_id, register_code_id]
  manyToOne:
    register_code:
      targetEntity: CodeGenerator\Domain\Model\RegisterCode\RegisterCode
      inversedBy: user_code
      joinColumn:
        name: register_code_id
        referencedColumnName: id
        onDelete: RESTRICT
        onUpdate: RESTRICT
        nullable: false
      cascade: ["persist", "merge"]
  oneToOne:
    coupon:
      targetEntity: CodeGenerator\Domain\Model\Coupon\Coupon
      inversedBy: user_code
      joinColumn:
        name: coupon_id
        referencedColumnName: id
        onDelete: NO ACTION
        onUpdate: NO ACTION
        nullable: true
      cascade: ["persist", "merge"]
    wp_user:
      targetEntity: CodeGenerator\Domain\Model\WpUsers\WpUsers
      joinColumn:
        name: wp_users_id
        referencedColumnName: ID
        onDelete: NO ACTION
        onUpdate: NO ACTION
        nullable: false
